### ISSUE TITLE
Image size annotations are different from the actual images

### ISSUE THREAD

**Issue by OatmealLiu** [visipedia/inat_loc#2]
Hi!

Thanks for sharing iNatLoc500 dataset with the perfect hierarchical information! I found it very useful and helpful as an evaluation set for detection tasks.

I am actually using iNatLoc500 dataset for my research. I found the image sizes annotation provided in the dataset is quiet different from the actual image sizes. The difference are mainly caused by the swapped width and height fields in the annotation.

For instance, the test image named "test/Actinopterygii/Cyprinus carpio/05405c328abddbcbbf7596d33b7074d7.jpg" has annotation "test/Actinopterygii/Cyprinus carpio/05405c328abddbcbbf7596d33b7074d7.jpg,800,600". But the actual image size is w=800, h=600 as shown below:
![05405c328abddbcbbf7596d33b7074d7](https://github.com/visipedia/inat_loc/assets/73873130/230677d8-3619-4e70-ad92-ba01c78cb871)

In total, I found **12,085/12,500** erros in val split, and **12,066/12,500** in test split. I can make a pull request to upload the two .JSON files that recorded the difference between the annotation and the actual image sizes, and the corrected image size annotation files for val and test split. 

I'd like to ask, is this caused by some rotation in the image data? Moreoever, do the bounding boxes annotations for val and test split also have corresponding errors due to the swapping? Thanks for your answer in advance! It is very important for my evaluation to know if there are also annotation drifts in the bboxes.

Thanks,

Best regards,
Mingxuan Liu

**Comment by elijahcole** [comment]
Thank you for flagging this - I will check it out and get back to you!

**Comment by OatmealLiu** [comment]
Thanks a lot!

**Comment by elijahcole** [comment]
Apologies for the delay and thanks for the question! After taking a closer look, I do not think there are errors in the dataset. On my end, the image sizes (on disk) all match the annotations. 

My hypothesis is that the discrepancy is due to a little hiccup with how the annotation files are being parsed. As described [here](https://github.com/visipedia/inat_loc/tree/main/dataset#image_sizestxt), each from of `image_sizes.txt` looks like
```
path/to/image,image_height,image_width
```
but I suspect you may parsing each line as
```
path/to/image,image_width,image_height
```
in your code. I'm pretty sure this is it, since the number of "non-errors" you note in each split matches the number of square images in each split (i.e. images for which swapping width and height doesn't matter). 

Please re-open this issue if I've got this wrong and I'll be happy to dig deeper!
